# Meta Methods

In [29]:
# Import libraries 
import pandas as pd   # Optional: good package for manipulating data 
import sklearn  # Package with learning algorithms implemented

dfTrain = pd.read_csv(r'..\Datasets\training-dataset.csv')
dfTest = pd.read_csv(r'..\Datasets\testing-dataset.csv')

#Remove id

dfTrain = dfTrain.iloc[: , 1:]
dfTest = dfTest.iloc[: , 1:]
X_train, y_train = dfTrain.drop('y', axis=1), dfTrain["y"]
X_test, y_test = dfTest.drop('y', axis=1), dfTest["y"]

display(dfTrain.head())
display(dfTest.head())

,age,campaign,cons.conf.idx,cons.price.idx,contact,day_of_week,default_unknown,default_yes,duration,education_basic.6y,...,marital_married,marital_single,marital_unknown,month,nr.employed,pdays,poutcome_nonexistent,poutcome_success,previous,y
0,0.493827,0.054545,0.192469,0.269680,0.0,0.00,0.0,0.0,0.292312,0.0,...,1.0,0.0,0.0,0.222222,0.512287,1.0,1.0,0.0,0.0,0.0
1,0.419753,0.036364,0.602510,0.698753,1.0,0.75,0.0,0.0,0.707998,0.0,...,1.0,0.0,0.0,0.222222,0.859735,1.0,1.0,0.0,0.0,0.0
2,0.234568,0.036364,0.602510,0.698753,1.0,1.00,0.0,0.0,0.670573,0.0,...,1.0,0.0,0.0,0.222222,0.859735,1.0,1.0,0.0,0.0,0.0
3,0.246914,0.127273,0.338912,0.669135,0.0,0.75,0.0,0.0,0.427908,0.0,...,1.0,0.0,0.0,0.444444,1.000000,1.0,1.0,0.0,0.0,0.0
4,0.345679,0.000000,0.615063,0.484412,0.0,1.00,0.0,0.0,0.642239,0.0,...,1.0,0.0,0.0,0.555556,1.000000,1.0,1.0,0.0,0.0,0.0

,age,campaign,cons.conf.idx,cons.price.idx,contact,day_of_week,default_unknown,default_yes,duration,education_basic.6y,...,marital_married,marital_single,marital_unknown,month,nr.employed,pdays,poutcome_nonexistent,poutcome_success,previous,y
0,0.185185,0.000000,0.192469,0.269680,0.0,0.0,1.0,0.0,0.558171,0.0,...,1.0,0.0,0.0,0.222222,0.512287,1.0,1.0,0.0,0.0,0.0
1,0.197531,0.018182,0.338912,0.669135,0.0,1.0,1.0,0.0,0.546344,1.0,...,0.0,1.0,0.0,0.444444,1.000000,1.0,1.0,0.0,0.0,0.0
2,0.098765,0.072727,0.154812,0.340608,0.0,0.0,0.0,0.0,0.638682,0.0,...,0.0,0.0,0.0,0.111111,0.512287,1.0,1.0,0.0,0.0,1.0
3,0.209877,0.000000,0.192469,0.269680,0.0,1.0,0.0,0.0,0.475605,0.0,...,0.0,1.0,0.0,0.222222,0.512287,1.0,1.0,0.0,0.0,0.0
4,0.444444,0.109091,0.368201,0.389322,0.0,1.0,0.0,0.0,0.292312,0.0,...,1.0,0.0,0.0,0.888889,0.877883,1.0,1.0,0.0,0.0,0.0

## Random Forest

Now we are going to execute the random forest algorithm and see the accuracy and f-measure.

In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from statsmodels.stats.proportion import proportion_confint
import matplotlib.pyplot as plt

clf = RandomForestClassifier(n_estimators=200)
clf = clf.fit(X_train, y_train)
pred = clf.predict(X_test)

# Obtain accuracy score of learned classifier on test data
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print()
print("Accuracy:", sklearn.metrics.accuracy_score(y_test, pred))
print()
print(sklearn.metrics.classification_report(y_test, pred))

0.9144412565290958
[[11641   408]
 [  755   789]]

Accuracy: 0.9144412565290958

              precision    recall  f1-score   support

         0.0       0.94      0.97      0.95     12049
         1.0       0.66      0.51      0.58      1544

    accuracy                           0.91     13593
   macro avg       0.80      0.74      0.76     13593
weighted avg       0.91      0.91      0.91     13593

Now we are going to try with ExtraTreesClassifier in order to introduce more randomness in the random trees.

In [35]:
from sklearn.ensemble import ExtraTreesClassifier

clf = ExtraTreesClassifier(n_estimators=200)
clf = clf.fit(X_train, y_train)
pred = clf.predict(X_test)

# Obtain accuracy score of learned classifier on test data
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print()
print("Accuracy:", sklearn.metrics.accuracy_score(y_test, pred))
print()
print(sklearn.metrics.classification_report(y_test, pred))

0.9046568086515118
[[11702   347]
 [  949   595]]

Accuracy: 0.9046568086515118

              precision    recall  f1-score   support

         0.0       0.92      0.97      0.95     12049
         1.0       0.63      0.39      0.48      1544

    accuracy                           0.90     13593
   macro avg       0.78      0.68      0.71     13593
weighted avg       0.89      0.90      0.89     13593